# Generated by Django 5.2.16 on 2026-07-30 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puskesmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(blank=True, max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Puskesmas',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='PemeriksaanLaboratorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveSmallIntegerField()),
                ('bulan', models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elemen_data', models.CharField(max_length=255)),
                ('sub_kategori', models.CharField(blank=True, max_length=255, null=True)),
                ('jumlah_l', models.PositiveIntegerField(default=0)),
                ('jumlah_p', models.PositiveIntegerField(default=0)),
                ('puskesmas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='puskesmas.puskesmas')),
            ],
            options={
                'verbose_name': 'Laporan Pemeriksaan Laboratorium',
                'verbose_name_plural': 'Laporan Pemeriksaan Laboratorium',
            },
        ),
        migrations.CreateModel(
            name='Rujukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveSmallIntegerField()),
                ('bulan', models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_faskes_tujuan', models.CharField(max_length=255)),
                ('umum_l', models.PositiveIntegerField(default=0)),
                ('umum_p', models.PositiveIntegerField(default=0)),
                ('bpjs_l', models.PositiveIntegerField(default=0)),
                ('bpjs_p', models.PositiveIntegerField(default=0)),
                ('sktm_l', models.PositiveIntegerField(default=0)),
                ('sktm_p', models.PositiveIntegerField(default=0)),
                ('puskesmas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='puskesmas.puskesmas')),
            ],
            options={
                'verbose_name': 'Laporan Rujukan',
                'verbose_name_plural': 'Laporan Rujukan',
            },
        ),
        migrations.CreateModel(
            name='PenyakitTerbanyak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveSmallIntegerField()),
                ('bulan', models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peringkat', models.PositiveSmallIntegerField()),
                ('icd10', models.CharField(max_length=20)),
                ('diagnosa', models.CharField(max_length=255)),
                ('kasus_l', models.PositiveIntegerField(default=0)),
                ('kasus_p', models.PositiveIntegerField(default=0)),
                ('puskesmas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='puskesmas.puskesmas')),
            ],
            options={
                'verbose_name': 'Laporan 15 Besar Penyakit',
                'verbose_name_plural': 'Laporan 15 Besar Penyakit',
                'ordering': ['tahun', 'bulan', 'peringkat'],
                'unique_together': {('puskesmas', 'tahun', 'bulan', 'peringkat')},
            },
        ),
        migrations.CreateModel(
            name='KunjunganPasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveSmallIntegerField()),
                ('bulan', models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rajal_l', models.PositiveIntegerField(default=0)),
                ('rajal_p', models.PositiveIntegerField(default=0)),
                ('ranap_l', models.PositiveIntegerField(default=0)),
                ('ranap_p', models.PositiveIntegerField(default=0)),
                ('jiwa_l', models.PositiveIntegerField(default=0)),
                ('jiwa_p', models.PositiveIntegerField(default=0)),
                ('puskesmas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='puskesmas.puskesmas')),
            ],
            options={
                'verbose_name': 'Laporan Kunjungan Pasien',
                'verbose_name_plural': 'Laporan Kunjungan Pasien',
                'unique_together': {('puskesmas', 'tahun', 'bulan')},
            },
        ),
        migrations.CreateModel(
            name='KesehatanGigiMulut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveSmallIntegerField()),
                ('bulan', models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tumpatan_gigi_tetap', models.PositiveIntegerField(default=0)),
                ('pencabutan_gigi_tetap', models.PositiveIntegerField(default=0)),
                ('jumlah_kunjungan', models.PositiveIntegerField(default=0)),
                ('jumlah_kasus_gigi', models.PositiveIntegerField(default=0)),
                ('jumlah_kasus_dirujuk', models.PositiveIntegerField(default=0)),
                ('puskesmas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='puskesmas.puskesmas')),
            ],
            options={
                'verbose_name': 'Laporan Kesehatan Gigi & Mulut',
                'verbose_name_plural': 'Laporan Kesehatan Gigi & Mulut',
                'unique_together': {('puskesmas', 'tahun', 'bulan')},
            },
        ),
    ]
